### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Vancouver_Bike_Theft_Analysis#14]
@makka3 @Jamienie
You have made lots of great additions to your analysis for this milestone. Overall, you have done a good job! 

Here are some remaining issues:

- [ ] Get rid of the proposal structure on the main readme. You no longer have an "Analysis Plan". You have the analysis. So explain your analysis. Same applies to the "Visualization" section on the readme. I can also suggest changing the future tense in your statements. Same thing applies for your report.
- [ ] Add a link to your report on the main readme 
- [ ] Add version information to your dependencies
- [ ] Fix the broken links within the sentence "Imported data can be found here, in the src folder of our repository, and a snippet of it can be found here." in the Dataset section on your readme
- [ ] Figure 1 in your report looks problematic. It does not match your description. There is no movement in the data within the figure. Fix the problem and also change the axes to make them more intuitive. Use 1,2,...,12 to represent months instead of decimal numbers such as 2.5, 3.5, ..., 12.5
- [ ] Add links in your report whenever you mention a specific folder/file within your repository.

**Suggestions:**

- You have mentioned your github name on the main readme. Also add links to your profiles.
- You can include a flow chart/dependency diagram on your readme.
- Keep any sort of wrangled/processed data in the `results` folder rather than the data folder
- Figure 2 seemed a bit too large within the report, you might want to resize that.
- You can add a section titled "Exploratory Data Analysis" within your report where you present your exploratory visualizations.

**Comment by makka3** [comment]
For Milestone 2, the following changes were made to the project to reflect your suggestions including:
- Cleaning the Readme + adding dependencies + diagram
- Improving the visualizations in the report
- Make file
- Editing the report

Thank you once again for your suggestions.
